version: "3.2"
services: 
  web:
    build:
      context: ./docker/develop/web
    container_name: ${PROJECT_NAME}_web
    ports:
      - ${WEB_PORT}:80
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    volumes:
      - .:/root/app
      - ./docker/develop/ssh:/root/.ssh
      - ./docker/develop/git:/root/.git
      - ./docker/develop/git/.gitconfig:/root/.gitconfig:ro
      - ./code:/var/www/app
      - ./docker/develop/web/000-default.conf:/etc/apache2/sites-enabled/000-default.conf

  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/develop/mysql/init/:/docker-entrypoint-initdb.d/
    container_name: ${PROJECT_NAME}_mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: ${PROJECT_NAME}_mailhog
    ports:
      - ${MAILHOG_SMPT_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025

volumes:
  mysql-data:
