version: "3.2"
services: 
  web:
    build:
      context: ./docker/develop/web
    container_name: ${PROJECT_NAME}_web
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./code:/var/www/app
      - ./docker/develop/web/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
