name: develop pipeline

on:
  push:
    branches: ["main", "develop", "staging"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: ['*']
    paths-ignore:
      - "*.md"

jobs:
  develop:
    runs-on: ubuntu-20.04
    name: Test - PHP 8.1
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'la_placita_test'
          mysql user: 'laravel'
          mysql password: root
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --silent; do
            sleep 0.2
          done
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: code/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none
      - name: Install PHP CodeSniffer
        run: |
          curl -L -o /usr/local/bin/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar 
          php /usr/local/bin/phpcs --version
          cd code
          php /usr/local/bin/phpcs
      - name: Setup and test
        run: | 
          cd code
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          vendor/bin/phpunit --verbose --testdox
