name: ci/cd pipeline

on:
  push:
      branches:
        - main
        - features/*
  pull_request:
    
jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: dummy
        run: echo "Execute lint"

  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [8.1]
    name: Test - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none
      - name: Setup and test
        run: | 
          cd code
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          vendor/bin/phpunit --verbose

  e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: dummy
        run: echo "Execute e2e"

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: dummy
        run: echo "Execute deploy"
